### 1. Listar todos los desarrolladores
GET http://localhost:3000/desarrolladores

### 2. Ver juegos de un desarrollador (ID=2)
GET http://localhost:3000/desarrolladores/2/juegos



### 3. Actualizar desarrollador completo
PUT http://localhost:3000/desarrolladores/2
Content-Type: application/json

{
  "nombre": "Nintendo EPD Team",
  "pais": "Japón",
  "fundacion": "1984-01-01"
}

### 4. Actualizar solo el país
PUT http://localhost:3000/desarrolladores/1/pais
Content-Type: application/json

{
  "pais": "Japón 🇯🇵"
}
